
BIN_OUTPUT_PATH = bin
TOOL_BIN = bin/gotools/$(shell uname -s)-$(shell uname -m)
UNAME_S ?= $(shell uname -s)

build:
	rm -f $(BIN_OUTPUT_PATH)/velodyne-go-module
	go build $(LDFLAGS) -o $(BIN_OUTPUT_PATH)/velodyne-go-module main.go

module.tar.gz: build
	rm -f $(BIN_OUTPUT_PATH)/module.tar.gz
	tar czf $(BIN_OUTPUT_PATH)/module.tar.gz $(BIN_OUTPUT_PATH)/velodyne-go-module

velodyne-go-module: *.go 
	go build -o velodyne-go-module *.go

setup:
	if [ "$(UNAME_S)" = "Linux" ]; then \
		sudo apt install -y libjpeg-dev pkg-config; \
	fi

clean:
	rm -rf $(BIN_OUTPUT_PATH)/velodyne-go-module $(BIN_OUTPUT_PATH)/module.tar.gz velodyne-go-module

gofmt:
	gofmt -w -s .

lint: gofmt
	go mod tidy

update-rdk:
	go get go.viam.com/rdk@latest
	go mod tidy
